apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached
    spec:
      hostNetwork: True
      nodeSelector:
          nodeType: controller
      containers:
        - name: memcached
          image: registry:5000/ec/memcached
          ports:
          - containerPort: 11211
          args: [ "-u", "memcached", "-m", "20480", "-c", "20000", 'controller60' ]
