apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glance-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: glance-controller
    spec:
      hostNetwork: True
      nodeSelector:
          nodeType: controller
      containers:
        - name: glance-api
          image: registry:5000/ec/glance-api
          ports:
          - containerPort: 9292
          volumeMounts:
            - {mountPath: /etc/hosts, name: etc-hosts }
            - {mountPath: /etc/glance, name: etc-glance }
            - {mountPath: /var/log/glance, name: var-log-glance }
            - {mountPath: /var/lib/glance, name: var-lib-glanc }
            - {mountPath: /etc/ceph, name: etc-ceph }
        - name: glance-registry
          image: registry:5000/ec/glance-registry
          volumeMounts:
            - {mountPath: /etc/hosts, name: etc-hosts }
            - {mountPath: /etc/glance, name: etc-glance }
            - {mountPath: /var/log/glance, name: var-log-glance }
            - {mountPath: /var/lib/glance, name: var-lib-glanc }
            - {mountPath: /etc/ceph, name: etc-ceph }
      volumes:
        - {name: etc-hosts, hostPath: {path: /etc/hosts}}
        - {name: etc-glance, hostPath: {path: /etc/glance}}
        - {name: var-lib-glanc, hostPath: {path: /var/lib/glance}}
        - {name: var-log-glance, hostPath: {path: /var/log/glance}}
        - {name: etc-ceph, hostPath: {path: /etc/ceph}}
